export const COLLEGE_COURSES = [
  "Bachelor of Science in Accountancy",
  "Bachelor of Science in Agriculture",
  "Bachelor of Science in Architecture",
  "Bachelor of Arts in English",
  "Bachelor of Arts in Journalism",
  "Bachelor of Arts in Mass Communication",
  "Bachelor of Arts in Sociology",
  "Bachelor of Fine Arts",
  "Bachelor of Library and Information Science",
  "Bachelor of Physical Education",
  "Bachelor of Public Administration",
  "Bachelor of Science in Biology",
  "Bachelor of Science in Business Administration",
  "Bachelor of Science in Chemical Engineering",
  "Bachelor of Science in Chemistry",
  "Bachelor of Science in Civil Engineering",
  "Bachelor of Science in Computer Engineering",
  "Bachelor of Science in Computer Science",
  "Bachelor of Science in Criminology",
  "Bachelor of Science in Education",
  "Bachelor of Science in Electrical Engineering",
  "Bachelor of Science in Electronics and Communications Engineering",
  "Bachelor of Science in Entrepreneurship",
  "Bachelor of Science in Environmental Science",
  "Bachelor of Science in Geodetic Engineering",
  "Bachelor of Science in Geology",
  "Bachelor of Science in Hospitality Management",
  "Bachelor of Science in Human Resource Management",
  "Bachelor of Science in Industrial Engineering",
  "Bachelor of Science in Information Technology",
  "Bachelor of Science in Legal Management",
  "Bachelor of Science in Management Accounting",
  "Bachelor of Science in Marketing Management",
  "Bachelor of Science in Mathematics",
  "Bachelor of Science in Mechanical Engineering",
  "Bachelor of Science in Medical Technology",
  "Bachelor of Science in Midwifery",
  "Bachelor of Science in Mining Engineering",
  "Bachelor of Science in Nursing",
  "Bachelor of Science in Nutrition and Dietetics",
  "Bachelor of Science in Occupational Therapy",
  "Bachelor of Science in Pharmacy",
  "Bachelor of Science in Physical Therapy",
  "Bachelor of Science in Physics",
  "Bachelor of Science in Political Science",
  "Bachelor of Science in Psychology",
  "Bachelor of Science in Radiologic Technology",
  "Bachelor of Science in Respiratory Therapy",
  "Bachelor of Science in Social Work",
  "Bachelor of Science in Statistics",
  "Bachelor of Science in Tourism Management"
];


export const TECHNICAL_VOCATIONAL_COURSES = [
  "Agricultural Crops Production NC II",
  "Animal Production (Swine) NC II",
  "Automotive Servicing NC I",
  "Automotive Servicing NC II",
  "Baking NC II",
  "Barista NC II",
  "Bartending NC II",
  "Beauty Care (Nail Care) NC II",
  "Beauty Care (Skin Care) NC II",
  "Beauty Care NC II",
  "Bread and Pastry Production NC II",
  "Carpentry NC II",
  "Consumer Electronics Servicing NC II",
  "Cookery NC II",
  "Dressmaking NC II",
  "Driving NC II",
  "Electrical Installation and Maintenance NC II",
  "Electronics Products Assembly and Servicing NC II",
  "Events Management NC III",
  "Food and Beverage Services NC II",
  "Front Office Services NC II",
  "Hairdressing NC II",
  "Handicraft Making (Basketry) NC II",
  "Handicraft Making (Macrame) NC II",
  "Handicraft Making (Pottery/Ceramics) NC II",
  "Heavy Equipment Operation NC II",
  "Hilot (Wellness Massage) NC II",
  "Housekeeping NC II",
  "Illustration NC III",
  "Landscaping NC II",
  "Machining NC I",
  "Machining NC II",
  "Masonry NC I",
  "Masonry NC II",
  "Massage Therapy NC II",
  "Organic Agriculture Production NC II",
  "Painting NC II",
  "Plumbing NC I",
  "Plumbing NC II",
  "Shielded Metal Arc Welding NC I",
  "Shielded Metal Arc Welding NC II",
  "Tile Setting NC I",
  "Tile Setting NC II",
  "Tour Guiding Services NC II",
  "Transport and Delivery Services NC II",
  "Visual Graphic Design NC III"
];


export const ALS_SECONDARY_COURSES = [
  "Bachelor of Science in Accountancy",
  "Bachelor of Science in Agriculture",
  "Bachelor of Science in Architecture",
  "Bachelor of Science in Biology",
  "Bachelor of Science in Business Administration",
  "Bachelor of Science in Computer Science",
  "Bachelor of Science in Criminology",
  "Bachelor of Secondary Education",
  "Bachelor of Science in Engineering",
  "Bachelor of Science in Hospitality Management",
  "Bachelor of Science in Information Technology",
  "Bachelor of Science in Nursing",
  "Bachelor of Science in Tourism Management"
];

export const COLLEGE_UNDERGRADUATE_COURSES = [
  "Bachelor of Science in Accountancy",
  "Bachelor of Science in Agriculture",
  "Bachelor of Science in Architecture",
  "Bachelor of Arts in English",
  "Bachelor of Arts in Journalism",
  "Bachelor of Arts in Mass Communication",
  "Bachelor of Arts in Sociology",
  "Bachelor of Fine Arts",
  "Bachelor of Library and Information Science",
  "Bachelor of Physical Education",
  "Bachelor of Public Administration",
  "Bachelor of Science in Biology",
  "Bachelor of Science in Business Administration",
  "Bachelor of Science in Chemical Engineering",
  "Bachelor of Science in Chemistry",
  "Bachelor of Science in Civil Engineering",
  "Bachelor of Science in Computer Engineering",
  "Bachelor of Science in Computer Science",
  "Bachelor of Science in Criminology",
  "Bachelor of Science in Education",
  "Bachelor of Science in Electrical Engineering",
  "Bachelor of Science in Electronics and Communications Engineering",
  "Bachelor of Science in Entrepreneurship",
  "Bachelor of Science in Environmental Science",
  "Bachelor of Science in Geodetic Engineering",
  "Bachelor of Science in Geology",
  "Bachelor of Science in Hospitality Management",
  "Bachelor of Science in Human Resource Management",
  "Bachelor of Science in Industrial Engineering",
  "Bachelor of Science in Information Technology",
  "Bachelor of Science in Legal Management",
  "Bachelor of Science in Management Accounting",
  "Bachelor of Science in Marketing Management",
  "Bachelor of Science in Mathematics",
  "Bachelor of Science in Mechanical Engineering",
  "Bachelor of Science in Medical Technology",
  "Bachelor of Science in Midwifery",
  "Bachelor of Science in Mining Engineering",
  "Bachelor of Science in Nursing",
  "Bachelor of Science in Nutrition and Dietetics",
  "Bachelor of Science in Occupational Therapy",
  "Bachelor of Science in Pharmacy",
  "Bachelor of Science in Physical Therapy",
  "Bachelor of Science in Physics",
  "Bachelor of Science in Political Science",
  "Bachelor of Science in Psychology",
  "Bachelor of Science in Radiologic Technology",
  "Bachelor of Science in Respiratory Therapy",
  "Bachelor of Science in Social Work",
  "Bachelor of Science in Statistics",
  "Bachelor of Science in Tourism Management"
];
